services:
  mongo:
    image: mongo
    restart: no
    environment:
      MONGO_INITDB_ROOT_USERNAME: skyticket
      MONGO_INITDB_ROOT_PASSWORD: skyticket
    volumes:
        - mongo-data:/data/db
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongo-data: