name: Build and Push Docker Image
on:
    push:
        branches:
        - main
    workflow_dispatch: {}
jobs:
    build:
      strategy:
        matrix:
          include:
            - arch: amd64
              os: ubuntu-latest
            - arch: arm64
              os: ubuntu-24.04-arm
      runs-on: ${{ matrix.os }}
      steps:
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ghcr.io/enxg/skyticket:${{ matrix.arch }}
            platforms: linux/${{ matrix.arch }}
            provenance: false
            sbom: false
    publish:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Create and push manifest list
          run: |
            docker manifest create ghcr.io/enxg/skyticket:latest \
              --amend ghcr.io/enxg/skyticket:amd64 \
              --amend ghcr.io/enxg/skyticket:arm64
            docker manifest push ghcr.io/enxg/skyticket:latest