name: Build and Push Docker Image
on:
    push:
        branches:
        - main
    workflow_dispatch: {}
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
          - name: Login to GitHub Container Registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
          - name: Login to DockerHub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              push: true
              tags: ghcr.io/enxg/skyticket:latest
              platforms: linux/amd64,linux/arm64
